export const announcements = [
  {
    id: 1,
    category: "Academic",
    tone: "blue",
    title: "Midterm Examination Schedule",
    copy: "Exam dates, times, rooms, and instructions for students.",
    source: "Office of the Registrar",
    time: "2 hours ago",
    important: true,
  },
  {
    id: 2,
    category: "Campus update",
    tone: "violet",
    title: "New Club Formation",
    copy: "AUST recently announced the formation of the AUST Model United Nations Cell and AUST Cybersecurity and AI Club.",
    source: "University Library",
    time: "Yesterday",
  },
  {
    id: 3,
    category: "Opportunity",
    tone: "amber",
    title: "Research Grant Opportunity",
    copy: "Call for students to submit research proposals through the AUST Student Research Grant.",
    source: "Research & Innovation",
    time: "Dec 4",
  },
  {
    id: 4,
    category: "Student life",
    tone: "green",
    title: "Club Recruitment",
    copy: "Recruitment for AUST Model United Nations Cell.",
    source: "Student Affairs",
    time: "Dec 2",
  },
];

export const events = [
  {
    id: 1,
    month: "DEC",
    date: "12",
    title: "AUST Career Fair",
    time: "10:00 AM – 4:00 PM",
    place: "AUST Auditorium",
    attendees: 84,
    category: "Career",
    color: "violet",
  },
  {
    id: 2,
    month: "DEC",
    date: "14",
    title: "CSE Carnival 6.0",
    time: "6:30 PM – 8:00 PM",
    place: "AUST Multipurpose Hall",
    attendees: 32,
    category: "Workshop",
    color: "blue",
  },
  {
    id: 3,
    month: "DEC",
    date: "18",
    title: "AUST Inter-Department Sports Festival",
    time: "3:00 PM – 6:00 PM",
    place: "AUST Sports Ground",
    attendees: 57,
    category: "Sports",
    color: "orange",
  },
  {
    id: 4,
    month: "JAN",
    date: "08",
    title: "Blood Donation & Social Welfare Program",
    time: "5:30 PM – 7:30 PM",
    place: "AUST Campus Courtyard",
    attendees: 118,
    category: "Community",
    color: "pink",
  },
];

export const marketplaceItems = [
  {
    id: 1,
    title: "Calculus: Early Transcendentals",
    price: "৳2400",
    detail: "Like new · 9th edition",
    category: "Books",
    seller: "Adnan",
    hue: "blue",
    icon: "BOOK",
  },
  {
    id: 2,
    title: "Scientific calculator",
    price: "৳1800",
    detail: "Casio fx-991EX · Excellent",
    category: "Academic",
    seller: "Nowfel",
    hue: "violet",
    icon: "fx",
  },
  {
    id: 3,
    title: "Desk lamp",
    price: "৳1200",
    detail: "Warm light · Adjustable arm",
    category: "Home",
    seller: "Jayed",
    hue: "amber",
    icon: "LAMP",
  },
  {
    id: 4,
    title: "Campus hoodie",
    price: "৳1600",
    detail: "Medium · Worn twice",
    category: "Fashion",
    seller: "Imran",
    hue: "pink",
    icon: "UNI",
  },
  {
    id: 5,
    title: "USB-C hub",
    price: "৳1500",
    detail: "HDMI + USB 3.0 ports",
    category: "Tech",
    seller: "Tahsin",
    hue: "green",
    icon: "USB",
  },
  {
    id: 6,
    title: "Biology lab coat",
    price: "৳900",
    detail: "Size S · Freshly cleaned",
    category: "Academic",
    seller: "Rafi",
    hue: "orange",
    icon: "LAB",
  },
];

export const foundItems = [
  {
    id: 1,
    status: "Found",
    title: "Black wireless earbuds",
    area: "Found near the North Library entrance",
    date: "Today, 11:40 AM",
    hue: "violet",
    icon: "◖◗",
  },
  {
    id: 2,
    status: "Lost",
    title: "Silver water bottle",
    area: "Last seen in room 7A03",
    date: "Yesterday",
    hue: "blue",
    icon: "H₂O",
  },
  {
    id: 3,
    status: "Found",
    title: "Student ID card",
    area: "Handed in at the Student Commons desk",
    date: "Dec 8",
    hue: "green",
    icon: "ID",
  },
  {
    id: 4,
    status: "Lost",
    title: "Grey knit scarf",
    area: "Last seen around the Arts courtyard",
    date: "Dec 7",
    hue: "amber",
    icon: "~",
  },
];

export function ItemArtwork({ label, hue }) {
  return (
    <div className={`item-artwork item-artwork--${hue}`} aria-hidden="true">
      <span>{label}</span>
    </div>
  );
}
